# Generated by Django 6.0.1 on 2026-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_image_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='property_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Apartment', 'Apartment'), ('Hostel', 'Hostel')], default='Room', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Shared', 'Shared'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], max_length=20),
        ),
    ]
